version: "3.8"
services:
  go:
    container_name: go
    build: ./golang
    tty: true
    ports:
      - "8080:8080"
    env_file:
      - ./mysql/.env
    depends_on:
      - db
    volumes:
      - ./golang/app:/go/src/app
    networks:
      - golang_network

  db:
    container_name: db
    build: ./mysql
    tty: true
    platform: linux/amd64
    ports:
      - 3306:3306
    env_file:
      - ./mysql/.env
    volumes:
      - mysql_volume:/var/lib/mysql
    networks:
      - golang_network

volumes:
  mysql_volume:
    name: mysql_volume

networks:
  golang_network:
    external: true